### ISSUE TITLE
TypeError: content.trimEnd is not a function

### ISSUE THREAD

**Issue by UlyC** [syroegkin/swagger-markdown#150]
```
TypeError: content.trimEnd is not a function
    at handleRunEnd (/home/hughes/.nvm/versions/node/v8.16.2/lib/node_modules/swagger-markdown/node_modules/markdownlint/lib/md037.js:38:27)
    at MD037.forEachLine (/home/hughes/.nvm/versions/node/v8.16.2/lib/node_modules/swagger-markdown/node_modules/markdownlint/lib/md037.js:142:13)
    at forMetadata (/home/hughes/.nvm/versions/node/v8.16.2/lib/node_modules/swagger-markdown/node_modules/markdownlint/helpers/helpers.js:259:5)
    at Array.forEach (<anonymous>)
    at forEachLine (/home/hughes/.nvm/versions/node/v8.16.2/lib/node_modules/swagger-markdown/node_modules/markdownlint/helpers/helpers.js:257:16)
    at Object.MD037 [as function] (/home/hughes/.nvm/versions/node/v8.16.2/lib/node_modules/swagger-markdown/node_modules/markdownlint/lib/md037.js:71:5)
    at forRule (/home/hughes/.nvm/versions/node/v8.16.2/lib/node_modules/swagger-markdown/node_modules/markdownlint/lib/markdownlint.js:593:20)
    at Array.forEach (<anonymous>)
    at lintContent (/home/hughes/.nvm/versions/node/v8.16.2/lib/node_modules/swagger-markdown/node_modules/markdownlint/lib/markdownlint.js:639:14)
    at lintNextItem (/home/hughes/.nvm/versions/node/v8.16.2/lib/node_modules/swagger-markdown/node_modules/markdownlint/lib/markdownlint.js:746:9)
```

**Comment by UlyC** [comment]
Above this problem  is  in the wsl2 environment,  When I switch to windows , everything  is ok.

**Comment by syroegkin** [comment]
Well this is interesting issue. Although I have no possibility to test this as I have no experience with wsl2 neither windows OS around.
Also seems like this issue is firing in [markdownlint](https://github.com/DavidAnson/markdownlint) library which is a dependency of swagger-markdown.
If you could reproduce this issue apart from swagger-markdown it would be very nice if you can submit issue to markdownlint library. Unfortunately I can not provide details to them on request with traces and logs.

Thank you for submitting this report!
