### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by peter-miroshnikov** [syroegkin/swagger-markdown#168]
```
 swagger-markdown -i ./openapi.yaml
RangeError: Maximum call stack size exceeded
    at Url.parse (node:url:170:37)
    at urlParse (node:url:158:13)
    at Object.urlResolve [as resolve] (node:url:674:10)
    at $Refs._resolve (/usr/local/lib/node_modules/swagger-markdown/node_modules/@apidevtools/json-schema-ref-parser/lib/refs.js:147:21)
    at $Refs.get (/usr/local/lib/node_modules/swagger-markdown/node_modules/@apidevtools/json-schema-ref-parser/lib/refs.js:98:15)
    at partiallyDereference (/usr/local/lib/node_modules/swagger-markdown/bin/convert.js:44:43)
    at partiallyDereference (/usr/local/lib/node_modules/swagger-markdown/bin/convert.js:46:20)
    at partiallyDereference (/usr/local/lib/node_modules/swagger-markdown/bin/convert.js:46:20)
    at partiallyDereference (/usr/local/lib/node_modules/swagger-markdown/bin/convert.js:46:20)
    at partiallyDereference (/usr/local/lib/node_modules/swagger-markdown/bin/convert.js:44:16)
```
on around 800 lines of yaml.

**Comment by syroegkin** [comment]
May I get access to this file (800+ lines) if possible?

**Comment by OlegoO** [comment]
Same problem with this file:

swagger-markdown -i VirtoCommerce.DynamicAssociationsModule.yaml
RangeError: Maximum call stack size exceeded
    at Pointer.resolve (C:\Users\OlegZhuk\AppData\Roaming\npm\node_modules\swagger-markdown\node_modules\@apidevtools\json-schema-ref-parser\lib\pointer.js:76:24)
 

[VirtoCommerce.DynamicAssociationsModule.yaml.txt](https://github.com/syroegkin/swagger-markdown/files/8804011/VirtoCommerce.DynamicAssociationsModule.yaml.txt)

**Comment by syroegkin** [comment]
Thank you for an example! very helpful.
This issue will be fixed with a next major release.
