### ISSUE TITLE
markdownlint.json issue

### ISSUE THREAD

**Issue by nzin-appdirect** [syroegkin/swagger-markdown#177]
I am using swagger-merger, which use swagger-markdown

With the new latest version (1.4.5) I have an issue:

```
yarn global add swagger-merger
npx swagger-markdown -i bundle.yaml -o README.md
...
npm WARN exec The following package was not found and will be installed: swagger-markdown

internal/modules/cjs/loader.js:818

  throw err;

  ^



Error: Cannot find module '../.markdownlint.json'

Require stack:

- /home/golang/.npm/_npx/529cdd1e3bb539d4/node_modules/swagger-markdown/bin/convert.js

- /home/golang/.npm/_npx/529cdd1e3bb539d4/node_modules/swagger-markdown/bin/index.js

    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)

    at Function.Module._load (internal/modules/cjs/loader.js:667:27)

    at Module.require (internal/modules/cjs/loader.js:887:19)

    at require (internal/modules/cjs/helpers.js:74:18)

    at Object.<anonymous> (/home/golang/.npm/_npx/529cdd1e3bb539d4/node_modules/swagger-markdown/bin/convert.js:17:26)

    at Module._compile (internal/modules/cjs/loader.js:999:30)

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

    at Module.load (internal/modules/cjs/loader.js:863:32)

    at Function.Module._load (internal/modules/cjs/loader.js:708:14)

    at Module.require (internal/modules/cjs/loader.js:887:19) {

  code: 'MODULE_NOT_FOUND',

  requireStack: [

    '/home/golang/.npm/_npx/529cdd1e3bb539d4/node_modules/swagger-markdown/bin/convert.js',

    '/home/golang/.npm/_npx/529cdd1e3bb539d4/node_modules/swagger-markdown/bin/index.js'

  ]

}
```

**Comment by syroegkin** [comment]
@nzin-appdirect you may try to use exact version until is isn't fixed. 1.4.3 should work just fine.

**Comment by syroegkin** [comment]
@nzin-appdirect please confirm the issue is get fixed

**Comment by nzin-appdirect** [comment]
Thanks @syroegkin , indeed it seems to be fixed :-)

Thank you
