### ISSUE TITLE
Does not support int8 type

### ISSUE THREAD

**Issue by wuqinqiang** [syroegkin/swagger-markdown#206]
**Is your feature request related to a problem? Please describe.**
```md
{
  stack: 'MissingPointerError: Token "int8" does not exist.\n' +
    '    at Pointer.resolve (/opt/homebrew/lib/node_modules/swagger-markdown/node_modules/@apidevtools/json-schema-ref-parser/lib/pointer.js:94:13)\n' +
    '    at $Ref.resolve (/opt/homebrew/lib/node_modules/swagger-markdown/node_modules/@apidevtools/json-schema-ref-parser/lib/ref.js:115:20)\n' +
    '    at $Refs._resolve (/opt/homebrew/lib/node_modules/swagger-markdown/node_modules/@apidevtools/json-schema-ref-parser/lib/refs.js:156:15)\n' +
    '    at inventory$Ref (/opt/homebrew/lib/node_modules/swagger-markdown/node_modules/@apidevtools/json-schema-ref-parser/lib/bundle.js:99:23)\n' +
    '    at crawl (/opt/homebrew/lib/node_modules/swagger-markdown/node_modules/@apidevtools/json-schema-ref-parser/lib/bundle.js:74:11)\n' +
    '    at crawl (/opt/homebrew/lib/node_modules/swagger-markdown/node_modules/@apidevtools/json-schema-ref-parser/lib/bundle.js:77:11)\n' +
    '    at crawl (/opt/homebrew/lib/node_modules/swagger-markdown/node_modules/@apidevtools/json-schema-ref-parser/lib/bundle.js:77:11)\n' +
    '    at crawl (/opt/homebrew/lib/node_modules/swagger-markdown/node_modules/@apidevtools/json-schema-ref-parser/lib/bundle.js:77:11)\n' +
    '    at bundle (/opt/homebrew/lib/node_modules/swagger-markdown/node_modules/@apidevtools/json-schema-ref-parser/lib/bundle.js:22:3)\n' +
    '    at SwaggerParser.bundle (/opt/homebrew/lib/node_modules/swagger-markdown/node_modules/@apidevtools/json-schema-ref-parser/lib/index.js:228:5)',
  code: 'EMISSINGPOINTER',
  message: 'Token "int8" does not exist.',
  ```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
-

**Comment by syroegkin** [comment]
@wuqinqiang may I please request the document example which causes this problem?
