### ISSUE TITLE
SecurityDefinitions...replace is not a function

### ISSUE THREAD

**Issue by F1LT3R** [syroegkin/swagger-markdown#98]
I receive the following error when trying to use your lib on yaml downloaded from the swagger site.

```shell
 swagger-markdown -i swagger.yaml

TypeError: securityDefinitions[type][value].replace is not a function
    at /Users/al/.nvm/versions/node/v6.11.1/lib/node_modules/swagger-markdown/bin/transformers/securityDefinitions.js:31:86
    at Array.map (native)
    at /Users/al/.nvm/versions/node/v6.11.1/lib/node_modules/swagger-markdown/bin/transformers/securityDefinitions.js:24:44
    at Array.map (native)
    at module.exports (/Users/al/.nvm/versions/node/v6.11.1/lib/node_modules/swagger-markdown/bin/transformers/securityDefinitions.js:20:36)
    at Object.<anonymous> (/Users/al/.nvm/versions/node/v6.11.1/lib/node_modules/swagger-markdown/bin/index.js:57:21)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

**Comment by tadimy** [comment]
same issue

**Comment by theBenForce** [comment]
Same issue for me.
